### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by VoipSip** [hax0rtahm1d/Encode#1]
hello sir can i ask about something i have source code i want to protected him from thief and i will rent them for people and i want to be control at him like make him working by every ip never access with any one without make the ip access from me if try any other ip to using my code without make him access from me say can't access talk to owner 

thank you i hope help me sir

**Comment by htr-tech** [comment]
@VoipSip google it .. you will be able to know this ... i will not help you accessing people's ip/ device database
